services:
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
    environment:
      DOMAIN: ${DOMAIN:-http://localhost}
      BACKEND_API_URL: ${BACKEND_API_URL}
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - green
      - blue
  blue:
    image: ghcr.io/menschmachine/pdfdancer-api:blue
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
      - "5005:5005"
    environment:
      COLOR: blue
      PDFDANCER_CONFIG_FILE: /conf/pdfdancer-config.yaml
    env_file:
      - .env
    healthcheck:
      test: curl --fail -q localhost:8080/ping
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./fonts:/home/app/fonts
      - ./conf:/conf
      - ./db:/db
  green:
    image: ghcr.io/menschmachine/pdfdancer-api:green
    restart: always
    ports:
      - "127.0.0.1:8081:8080"
      - "5006:5005"
    environment:
      COLOR: green
      PDFDANCER_CONFIG_FILE: /conf/pdfdancer-config.yaml
    env_file:
      - .env
    healthcheck:
      test: curl --fail -q localhost:8080/ping
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./fonts:/home/app/fonts
      - ./conf:/conf
      - ./db:/db
