services:
  caddy:
    image: caddy:2.8.4
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
    environment:
      DOMAIN: ${DOMAIN:-http://localhost}
      BACKEND_API_URL: ${BACKEND_API_URL}
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - green
      - blue

  blue:
    image: ghcr.io/menschmachine/pdfdancer-api:blue
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
      - "5005:5005"
    environment:
      COLOR: blue
      PDFDANCER_CONFIG_FILE: /conf/pdfdancer-config.yaml
      JAVA_TOOL_OPTIONS: >
        -Djava.io.tmpdir=/tmp
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./fonts:/home/app/fonts
      - ./conf:/conf:ro
      - db-shared:/db
      - tmp-blue:/tmp
      - ./async-profiler-4.1-linux-x64:/asprof:ro
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  green:
    image: ghcr.io/menschmachine/pdfdancer-api:green
    restart: always
    ports:
      - "127.0.0.1:8081:8080"
      - "5006:5005"
    environment:
      COLOR: green
      PDFDANCER_CONFIG_FILE: /conf/pdfdancer-config.yaml
      JAVA_TOOL_OPTIONS: >
        -Djava.io.tmpdir=/tmp
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./fonts:/home/app/fonts
      - ./conf:/conf:ro
      - db-shared:/db
      - tmp-green:/tmp
      - ./async-profiler-4.1-linux-x64:/asprof:ro
    logging:
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  db-shared:
  tmp-blue:
  tmp-green:
  caddy-data: